# -*- coding: utf-8 -*-
"""Transformer_Gradio_app_bacteria_stitching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YzI2Cg34Df-UOjU5NIvPZ1jv2A6ejXhr
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install gradio -q

import os
import re
import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from keras import layers
import gradio as gr
import matplotlib.pyplot as plt
import tempfile

!find /content/drive/MyDrive -name "Trained_Transformer_Model.keras"

MODEL_PATH = "/content/drive/MyDrive/Trained_Transformer_Model.keras"

if os.path.exists(MODEL_PATH):
    print("Model file found:", MODEL_PATH)
else:
    raise FileNotFoundError("Model file not found. Please check MODEL_PATH.")

@keras.saving.register_keras_serializable(package="Custom")
class TokenPositionalEmbedding(layers.Layer):
    def __init__(self, maxlen, d_model, **kwargs):
        super().__init__(**kwargs)
        self.maxlen = maxlen
        self.d_model = d_model
        self.pos_emb = layers.Embedding(
            input_dim=maxlen,
            output_dim=d_model,
            name="pos_emb"
        )

    def call(self, x):
        seq_len = tf.shape(x)[1]
        positions = tf.range(start=0, limit=seq_len, delta=1)
        positions = self.pos_emb(positions)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update({
            "maxlen": self.maxlen,
            "d_model": self.d_model
        })
        return config


@keras.saving.register_keras_serializable(package="Custom")
class TinyTransformerBlock(layers.Layer):
    def __init__(
        self,
        d_model=None,
        num_heads=None,
        ffn_dim=None,
        ff_dim=None,
        dropout=0.1,
        **kwargs
    ):
        super().__init__(**kwargs)

        if ffn_dim is None:
            ffn_dim = ff_dim

        self.d_model = d_model
        self.num_heads = num_heads
        self.ffn_dim = ffn_dim
        self.dropout = dropout

        self.mha = layers.MultiHeadAttention(
            num_heads=num_heads,
            key_dim=d_model // num_heads,
            name="mha"
        )

        self.ffn = keras.Sequential(
            [
                layers.Dense(ffn_dim, activation="relu"),
                layers.Dense(d_model),
            ],
            name="ffn"
        )

        self.ln1 = layers.LayerNormalization(epsilon=1e-6, name="ln1")
        self.ln2 = layers.LayerNormalization(epsilon=1e-6, name="ln2")

        self.dropout1 = layers.Dropout(dropout)
        self.dropout2 = layers.Dropout(dropout)

    def call(self, inputs, training=False):
        attn_output = self.mha(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)

        out1 = self.ln1(inputs + attn_output)

        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)

        return self.ln2(out1 + ffn_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "d_model": self.d_model,
            "num_heads": self.num_heads,
            "ffn_dim": self.ffn_dim,
            "dropout": self.dropout
        })
        return config

custom_objects = {
    "TokenPositionalEmbedding": TokenPositionalEmbedding,
    "TinyTransformerBlock": TinyTransformerBlock,
    "Custom>TokenPositionalEmbedding": TokenPositionalEmbedding,
    "Custom>TinyTransformerBlock": TinyTransformerBlock,
}

model = keras.models.load_model(
    MODEL_PATH,
    custom_objects=custom_objects,
    compile=False,
    safe_mode=False
)

model.summary()

print("Model input shape:", model.input_shape)
print("Model output shape:", model.output_shape)

CLASS_0 = "Substrate"
CLASS_1 = "Bacteria"

THRESHOLD = 0.5

TARGET_FEATURES = int(model.input_shape[1])

print("Class 0:", CLASS_0)
print("Class 1:", CLASS_1)
print("Target features required by model:", TARGET_FEATURES)

def extract_numbers(line):
    """
    Extracts integers and decimal numbers from a line.
    """
    return re.findall(r"[-+]?\d*\.\d+|[-+]?\d+", line)


def read_horiba_raman_txt(file_path, target_features=500):
    """
    Reads Horiba/XploRA Raman map TXT files.

    Expected format:
    - Metadata lines starting with #
    - One wavenumber header row
    - Data rows with: Y, X, intensity1, intensity2, ...

    Returns:
    - X_model: shape = samples × target_features × 1
    - info dictionary
    """

    with open(file_path, "rb") as f:
        raw = f.read()

    # latin1 avoids UTF-8 errors caused by symbols like cm-¹ and µm
    text = raw.decode("latin1", errors="ignore")
    lines = text.splitlines()

    header_idx = None
    wavenumbers = None

    # Find wavenumber row
    for i, line in enumerate(lines):
        if line.startswith("#"):
            continue

        nums = extract_numbers(line)

        if len(nums) > 100:
            values = np.array([float(x) for x in nums], dtype="float32")

            # Wavenumber row usually starts near 550 and ends near 2200
            if 500 <= values[0] <= 600 and 2100 <= values[-1] <= 2300:
                header_idx = i
                wavenumbers = values
                break

    if header_idx is None:
        raise ValueError(
            "Could not find the wavenumber header row. "
            "Please check if this is a Horiba Raman TXT file."
        )

    expected_len = len(wavenumbers)

    spectra = []
    coordinates = []

    # Read spectral rows after wavenumber header
    for line in lines[header_idx + 1:]:
        if not line.strip():
            continue

        if line.startswith("#"):
            continue

        nums = extract_numbers(line)

        # Data row should contain Y, X, and spectral intensities
        if len(nums) >= expected_len + 2:
            values = np.array(
                [float(x) for x in nums[:expected_len + 2]],
                dtype="float32"
            )

            coordinates.append(values[:2])
            spectra.append(values[2:])

    if len(spectra) == 0:
        raise ValueError("No spectral intensity rows found in the TXT file.")

    X_raw = np.array(spectra, dtype="float32")
    coordinates = np.array(coordinates, dtype="float32")

    original_spectra_count = X_raw.shape[0]
    original_features = X_raw.shape[1]

    # Remove completely zero spectra
    nonzero_mask = np.sum(np.abs(X_raw), axis=1) > 0

    X_raw = X_raw[nonzero_mask]
    coordinates = coordinates[nonzero_mask]

    removed_zero_spectra = original_spectra_count - X_raw.shape[0]

    if X_raw.shape[0] == 0:
        raise ValueError("All spectra are zero. No usable spectra found.")

    # Resample from original spectral length to model-required length
    if original_features != target_features:
        target_wavenumbers = np.linspace(
            wavenumbers.min(),
            wavenumbers.max(),
            target_features
        ).astype("float32")

        X_resampled = np.array(
            [
                np.interp(target_wavenumbers, wavenumbers, row)
                for row in X_raw
            ],
            dtype="float32"
        )
    else:
        X_resampled = X_raw

    # Shape expected by model: samples × features × 1
    X_model = np.expand_dims(X_resampled, axis=-1)

    info = {
        "original_spectra_count": int(original_spectra_count),
        "used_spectra_count": int(X_model.shape[0]),
        "removed_zero_spectra": int(removed_zero_spectra),
        "original_features": int(original_features),
        "model_features": int(target_features),
        "wavenumber_start": float(wavenumbers.min()),
        "wavenumber_end": float(wavenumbers.max())
    }

    return X_model, info

def read_generic_table_file(file_path, target_features=500):
    """
    Reads CSV/Excel files where rows are spectra and columns are features.
    Removes common coordinate/label columns.
    """

    if file_path.endswith(".csv"):
        df = pd.read_csv(file_path, encoding="latin1")
    elif file_path.endswith(".xlsx") or file_path.endswith(".xls"):
        df = pd.read_excel(file_path)
    else:
        raise ValueError("Unsupported file type for generic table reader.")

    df = df.dropna(axis=0, how="all")
    df = df.dropna(axis=1, how="all")

    remove_cols = [
        "X", "Y", "x", "y",
        "X_coord", "Y_coord", "x_coord", "y_coord",
        "Label", "label", "Class", "class"
    ]

    df = df.drop(columns=[c for c in remove_cols if c in df.columns], errors="ignore")

    numeric_df = df.apply(pd.to_numeric, errors="coerce")
    numeric_df = numeric_df.dropna(axis=0, how="all")
    numeric_df = numeric_df.dropna(axis=1, how="all")
    numeric_df = numeric_df.fillna(0)

    if numeric_df.shape[1] == 0:
        raise ValueError("No numeric spectral columns found.")

    X_raw = numeric_df.values.astype("float32")

    # Remove all-zero spectra
    nonzero_mask = np.sum(np.abs(X_raw), axis=1) > 0
    X_raw = X_raw[nonzero_mask]

    if X_raw.shape[0] == 0:
        raise ValueError("All rows are zero after cleaning.")

    original_features = X_raw.shape[1]

    # Resample if feature count is not equal to model input
    if original_features != target_features:
        old_axis = np.linspace(0, 1, original_features)
        new_axis = np.linspace(0, 1, target_features)

        X_resampled = np.array(
            [
                np.interp(new_axis, old_axis, row)
                for row in X_raw
            ],
            dtype="float32"
        )
    else:
        X_resampled = X_raw

    X_model = np.expand_dims(X_resampled, axis=-1)

    info = {
        "original_spectra_count": int(numeric_df.shape[0]),
        "used_spectra_count": int(X_model.shape[0]),
        "removed_zero_spectra": int(numeric_df.shape[0] - X_model.shape[0]),
        "original_features": int(original_features),
        "model_features": int(target_features),
        "wavenumber_start": None,
        "wavenumber_end": None
    }

    return X_model, info


def read_and_prepare_file(file_path, target_features=500):
    """
    Main reader used by the Gradio app.
    """

    file_path_lower = file_path.lower()

    if file_path_lower.endswith(".txt"):
        return read_horiba_raman_txt(file_path, target_features=target_features)

    elif file_path_lower.endswith(".csv") or file_path_lower.endswith(".xlsx") or file_path_lower.endswith(".xls"):
        return read_generic_table_file(file_path, target_features=target_features)

    else:
        raise ValueError("Please upload a TXT, CSV, XLSX, or XLS file.")

def make_probability_histogram(values, title, xlabel):
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(values, bins=20, alpha=0.8, edgecolor="black")
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Frequency")
    ax.grid(True, alpha=0.3)
    return fig


def make_percentage_bar_plot(class_0_count, class_1_count, total):
    class_0_percent = (class_0_count / total) * 100
    class_1_percent = (class_1_count / total) * 100

    fig, ax = plt.subplots(figsize=(6, 4))
    ax.bar([CLASS_0, CLASS_1], [class_0_percent, class_1_percent])
    ax.set_title("Percentage of Samples per Predicted Class")
    ax.set_xlabel("Predicted Class")
    ax.set_ylabel("Percentage (%)")
    ax.set_ylim(0, 100)

    for i, value in enumerate([class_0_percent, class_1_percent]):
        ax.text(i, value + 1, f"{value:.2f}%", ha="center")

    ax.grid(True, axis="y", alpha=0.3)
    return fig


def create_bacteria_only_stitched_file(X, predicted_labels, probabilities, original_file_path):
    """
    Keeps only spectra predicted as Bacteria and discards Substrate spectra.

    Here, "stitched" means the bacteria spectra are stacked together row-by-row
    into one new CSV file.

    The exported spectra are the same spectra used by the model:
    samples × model_features.
    """

    # Convert model input from samples × features × 1 to samples × features
    X_2d = np.squeeze(X, axis=-1)

    bacteria_mask = np.array(predicted_labels) == CLASS_1
    bacteria_spectra = X_2d[bacteria_mask]

    if bacteria_spectra.shape[0] == 0:
        return None, "No bacteria spectra were predicted, so no stitched file was created."

    bacteria_original_numbers = np.where(bacteria_mask)[0] + 1
    bacteria_probabilities = np.array(probabilities)[bacteria_mask] * 100

    feature_columns = [
        f"Feature_{i + 1}"
        for i in range(bacteria_spectra.shape[1])
    ]

    bacteria_df = pd.DataFrame(
        bacteria_spectra,
        columns=feature_columns
    )

    # Keep traceability to the original uploaded file
    bacteria_df.insert(0, "Bacteria_Probability (%)", bacteria_probabilities)
    bacteria_df.insert(0, "Original_Spectrum_Number", bacteria_original_numbers)

    # Also add one average bacteria spectrum at the end
    average_row = pd.DataFrame(
        [[
            "Average_Bacteria_Spectrum",
            float(np.mean(bacteria_probabilities)),
            *np.mean(bacteria_spectra, axis=0)
        ]],
        columns=["Original_Spectrum_Number", "Bacteria_Probability (%)", *feature_columns]
    )

    final_df = pd.concat([bacteria_df, average_row], ignore_index=True)

    base_name = os.path.splitext(os.path.basename(original_file_path))[0]
    safe_base_name = re.sub(r"[^A-Za-z0-9_\-]+", "_", base_name)

    output_path = os.path.join(
        tempfile.gettempdir(),
        f"{safe_base_name}_bacteria_only_stitched_spectra.csv"
    )

    final_df.to_csv(output_path, index=False)

    msg = (
        f"Bacteria-only stitched spectra file created.\n"
        f"Bacteria spectra kept: {bacteria_spectra.shape[0]}\n"
        f"Substrate spectra discarded: {len(predicted_labels) - bacteria_spectra.shape[0]}\n"
        f"An average bacteria spectrum was also added as the last row."
    )

    return output_path, msg


def make_average_bacteria_spectrum_plot(X, predicted_labels):
    """
    Plots the average spectrum from only the spectra predicted as Bacteria.
    """

    X_2d = np.squeeze(X, axis=-1)
    bacteria_mask = np.array(predicted_labels) == CLASS_1
    bacteria_spectra = X_2d[bacteria_mask]

    if bacteria_spectra.shape[0] == 0:
        return None

    avg_spectrum = np.mean(bacteria_spectra, axis=0)

    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(np.arange(1, len(avg_spectrum) + 1), avg_spectrum)
    ax.set_title("Average Spectrum After Keeping Only Bacteria Predictions")
    ax.set_xlabel("Model Feature Number")
    ax.set_ylabel("Mean Intensity")
    ax.grid(True, alpha=0.3)
    plt.tight_layout()

    return fig


def predict_substrate_vs_bacteria(file):
    try:
        if file is None:
            return "Please upload a file first.", None, None, None, None, None, None

        file_path = file.name

        X, info = read_and_prepare_file(
            file_path,
            target_features=TARGET_FEATURES
        )

        probabilities = model.predict(X, verbose=0).flatten()

        # If CLASS_1 = Bacteria, then model output probability is bacteria probability
        bacteria_probabilities = probabilities * 100
        substrate_probabilities = (1 - probabilities) * 100

        predicted_labels = []
        confidences = []

        for p in probabilities:
            p = float(p)

            if p >= THRESHOLD:
                predicted_labels.append(CLASS_1)
                confidences.append(p)
            else:
                predicted_labels.append(CLASS_0)
                confidences.append(1.0 - p)

        bacteria_keep_mask = np.array(predicted_labels) == CLASS_1

        result_df = pd.DataFrame({
            "Spectrum Number": np.arange(1, len(predicted_labels) + 1),
            "Predicted Class": predicted_labels,
            "Bacteria Probability (%)": bacteria_probabilities,
            "Substrate Probability (%)": substrate_probabilities,
            "Confidence (%)": np.array(confidences) * 100,
            "Kept in Bacteria-only File": bacteria_keep_mask
        })

        class_0_count = predicted_labels.count(CLASS_0)
        class_1_count = predicted_labels.count(CLASS_1)
        total = len(predicted_labels)

        mean_probability = float(np.mean(probabilities))

        if mean_probability >= THRESHOLD:
            final_prediction_by_probability = CLASS_1
            final_probability_confidence = mean_probability
        else:
            final_prediction_by_probability = CLASS_0
            final_probability_confidence = 1.0 - mean_probability

        if class_1_count > class_0_count:
            final_prediction_by_majority = CLASS_1
            majority_confidence = class_1_count / total
        elif class_0_count > class_1_count:
            final_prediction_by_majority = CLASS_0
            majority_confidence = class_0_count / total
        else:
            final_prediction_by_majority = "Tie"
            majority_confidence = 0.5

        if info["wavenumber_start"] is not None:
            wavenumber_text = f'{info["wavenumber_start"]:.2f} to {info["wavenumber_end"]:.2f} cm⁻¹'
        else:
            wavenumber_text = "Not available"

        stitched_file, stitched_message = create_bacteria_only_stitched_file(
            X=X,
            predicted_labels=predicted_labels,
            probabilities=probabilities,
            original_file_path=file_path
        )

        summary = f"""
Final File-Level Prediction: {final_prediction_by_majority}

Majority Confidence: {majority_confidence * 100:.2f}%

Prediction by Mean Probability: {final_prediction_by_probability}
Mean Probability Confidence: {final_probability_confidence * 100:.2f}%

Total spectra detected in file: {info["original_spectra_count"]}
Zero spectra removed: {info["removed_zero_spectra"]}
Spectra used for prediction: {info["used_spectra_count"]}

Original spectral features: {info["original_features"]}
Model input features: {info["model_features"]}

Wavenumber range: {wavenumber_text}

{CLASS_0} spectra: {class_0_count}
{CLASS_1} spectra: {class_1_count}

Mean bacteria probability: {mean_probability * 100:.2f}%
Mean substrate probability: {(1 - mean_probability) * 100:.2f}%
Decision threshold: {THRESHOLD}

Bacteria-only stitched file status:
{stitched_message}
"""

        bacteria_hist_fig = make_probability_histogram(
            bacteria_probabilities,
            "Predicted Probabilities for Bacteria",
            "Probability (%)"
        )

        substrate_hist_fig = make_probability_histogram(
            substrate_probabilities,
            "Predicted Probabilities for Substrate",
            "Probability (%)"
        )

        percentage_bar_fig = make_percentage_bar_plot(
            class_0_count,
            class_1_count,
            total
        )

        average_bacteria_fig = make_average_bacteria_spectrum_plot(
            X,
            predicted_labels
        )

        return (
            summary,
            result_df,
            bacteria_hist_fig,
            substrate_hist_fig,
            percentage_bar_fig,
            average_bacteria_fig,
            stitched_file
        )

    except Exception as e:
        return f"Error: {str(e)}", None, None, None, None, None, None

with gr.Blocks(title="Substrate vs Bacteria Classifier") as app:

    gr.Markdown("# Substrate vs Bacteria Classifier")

    gr.Markdown(
        """
Upload a Raman/SERS spectral file.

Supported formats:
- Horiba/XploRA `.txt`
- `.csv`
- `.xlsx`
- `.xls`

The model classifies each spectrum as **Substrate** or **Bacteria**.

After prediction, the app also creates a new CSV file where:
- only spectra predicted as **Bacteria** are kept
- spectra predicted as **Substrate** are discarded
- the kept bacteria spectra are stitched together row-by-row
- the average bacteria spectrum is added as the last row
"""
    )

    file_input = gr.File(
        label="Upload TXT / CSV / Excel file",
        file_types=[".txt", ".csv", ".xlsx", ".xls"]
    )

    predict_button = gr.Button("Predict and Create Bacteria-only Spectra")

    summary_output = gr.Textbox(
        label="Prediction Summary",
        lines=22
    )

    table_output = gr.Dataframe(
        label="Per-Spectrum Predictions",
        wrap=True
    )

    stitched_file_output = gr.File(
        label="Download Bacteria-only Stitched Spectra CSV"
    )

    gr.Markdown("## Prediction Graphs")

    bacteria_plot = gr.Plot(
        label="Predicted Probabilities for Bacteria"
    )

    substrate_plot = gr.Plot(
        label="Predicted Probabilities for Substrate"
    )

    percentage_plot = gr.Plot(
        label="Percentage of Samples per Predicted Class"
    )

    average_bacteria_plot = gr.Plot(
        label="Average Spectrum from Bacteria Predictions Only"
    )

    predict_button.click(
        fn=predict_substrate_vs_bacteria,
        inputs=file_input,
        outputs=[
            summary_output,
            table_output,
            bacteria_plot,
            substrate_plot,
            percentage_plot,
            average_bacteria_plot,
            stitched_file_output
        ]
    )

app.launch(
    share=True,
    debug=True
)

